// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'SECRET_API_KEY',
    appId: '1:56656986238:web:383d7b01dff3b928c4982f',
    messagingSenderId: '56656986238',
    projectId: 'save-token-firebase-300b2',
    authDomain: 'save-token-firebase-300b2.firebaseapp.com',
    storageBucket: 'save-token-firebase-300b2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'SECRET_API_KEY',
    appId: '1:56656986238:android:6eabd202a92a7580c4982f',
    messagingSenderId: '56656986238',
    projectId: 'save-token-firebase-300b2',
    storageBucket: 'save-token-firebase-300b2.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'SECRET_API_KEY',
    appId: '1:56656986238:web:2c51c3c1175e783bc4982f',
    messagingSenderId: '56656986238',
    projectId: 'save-token-firebase-300b2',
    authDomain: 'save-token-firebase-300b2.firebaseapp.com',
    storageBucket: 'save-token-firebase-300b2.firebasestorage.app',
  );
}
